CREATE SCHEMA IF NOT EXISTS quantic;

CREATE TABLE IF NOT EXISTS public.trading_bots
(
    id uuid PRIMARY KEY,
    name varchar(100) NOT NULL,
    symbol varchar(30) NOT NULL,
    exchange varchar(50) NOT NULL,
    strategy varchar(100) NOT NULL,
    allocation numeric(18,8) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Stopped',
    created_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.trading_bots
    ADD COLUMN IF NOT EXISTS last_evaluated_candle_utc timestamp without time zone;

CREATE TABLE IF NOT EXISTS quantic.bot_strategy_settings
(
    bot_id uuid PRIMARY KEY,
    account_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    timeframe varchar(10) NOT NULL DEFAULT '4h',
    fast_ema_period integer NOT NULL DEFAULT 50,
    slow_ema_period integer NOT NULL DEFAULT 200,
    rsi_period integer NOT NULL DEFAULT 14,
    atr_period integer NOT NULL DEFAULT 14,
    rsi_entry_min numeric(5,2) NOT NULL DEFAULT 40,
    rsi_entry_max numeric(5,2) NOT NULL DEFAULT 55,
    rsi_exit numeric(5,2) NOT NULL DEFAULT 70,
    atr_stop_multiplier numeric(8,4) NOT NULL DEFAULT 1.5,
    atr_take_profit_multiplier numeric(8,4) NOT NULL DEFAULT 3,
    risk_percent numeric(5,2) NOT NULL DEFAULT 1,
    is_enabled boolean NOT NULL DEFAULT true,
    updated_at_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bot_strategy_settings_bot_fkey FOREIGN KEY (bot_id)
        REFERENCES public.trading_bots (id) ON DELETE CASCADE,
    CONSTRAINT bot_strategy_settings_account_fkey FOREIGN KEY (account_id)
        REFERENCES quantic.paper_accounts (account_id),
    CONSTRAINT bot_strategy_settings_instrument_fkey FOREIGN KEY (instrument_id)
        REFERENCES quantic.instruments (instrument_id),
    CONSTRAINT bot_strategy_settings_periods_check CHECK (
        fast_ema_period > 0 AND slow_ema_period > fast_ema_period AND rsi_period > 0 AND atr_period > 0),
    CONSTRAINT bot_strategy_settings_risk_check CHECK (
        risk_percent > 0 AND risk_percent <= 100 AND atr_stop_multiplier > 0 AND atr_take_profit_multiplier > 0)
);

CREATE TABLE IF NOT EXISTS quantic.bot_positions
(
    bot_id uuid PRIMARY KEY,
    position_id bigint NOT NULL,
    entry_price numeric(18,6) NOT NULL,
    quantity numeric(18,6) NOT NULL,
    stop_loss numeric(18,6) NOT NULL,
    take_profit numeric(18,6) NOT NULL,
    opened_at_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bot_positions_bot_fkey FOREIGN KEY (bot_id)
        REFERENCES public.trading_bots (id) ON DELETE CASCADE,
    CONSTRAINT bot_positions_position_fkey FOREIGN KEY (position_id)
        REFERENCES quantic.positions (position_id)
);

CREATE TABLE IF NOT EXISTS quantic.bot_logs
(
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id uuid NOT NULL,
    level varchar(20) NOT NULL DEFAULT 'INFO',
    event_type varchar(50) NOT NULL,
    message varchar(500) NOT NULL,
    details jsonb,
    created_at_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bot_logs_bot_fkey FOREIGN KEY (bot_id)
        REFERENCES public.trading_bots (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_bot_logs_bot_id_created_at_utc
    ON quantic.bot_logs (bot_id, created_at_utc DESC);
